version: "3.7"
services:
  bootstrap-node:
    image: kadlab:latest
    stdin_open: true
    tty: true
    networks:
      - kademlia_network
    hostname: bootstrap-node

  joining-nodes:
    image: kadlab:latest
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 10s
    networks:
      - kademlia_network
    environment:
      - BOOTSTRAP_ADDRESS=bootstrap-node:8000
    depends_on:
      - bootstrap-node

networks:
  kademlia_network:

# To deploy the stack, use the command:
# docker stack deploy -c docker-compose.yml kadlab